# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_CONNECTION_URL: ${{secrets.MONGO_CONNECTION_URL}}
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Create credentials.json from secret
        env:
          CONFIG_INI: ${{ secrets.GOOGLE_CLOUD_STORAGE_BUCKET }}
        run: |
          echo "$GOOGLE_CLOUD_STORAGE_BUCKET" > credentials.json
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest  # Include flake8 for linting and pytest if needed
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Unit Tests with unittest
        run: |
          python manage.py test
